keys:
  - &admin_gatien age1200dtv77m23hxt7lnngnwezegfrx86hszascklwkk20uqrvmcfjss746as
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *admin_gatien
